import { z } from "zod";

export const carInsertSchema = z.object({
    id: z.string().optional(), // ID will be generated by the backend, so it's optional on the input side
    name: z.string().min(1, "Vehicle name is required"),
    make: z.string().min(1, "Make is required (e.g., Porsche)"),
    model: z.string().min(1, "Model is required (e.g., 911 Carrera)"),
    year: z
        .number()
        .int("Year must be a whole number")
        .min(1950, "Year is too old")
        .max(new Date().getFullYear() + 1, "Year cannot be too far in the future"),
    category: z.string().min(1, "Category is required"),

    pricePerDay: z
        .number()
        .int("Price must be a whole number (no decimals)")
        .min(0, "Price per day must be a positive number"),

    // REMOVED .default() - React Hook Form handles this now
    transmission: z.enum(["automatic", "manual"], "Transmission type is required and must be either 'automatic' or 'manual'"),

    // REMOVED .default()
    fuelType: z.enum(["petrol", "ev", "hybrid"], "Fuel type is required and must be one of: petrol, ev, hybrid"),

    seats: z
        .number()
        .int("Seats must be a whole number")
        .min(1, "Vehicle must have at least 1 seat")
        .max(60, "Exceeds maximum seat limit"),

    headerImage: z.url("Image must be a valid URL").optional(),

    imageUrls: z.array(z.url("Image urls")).optional(),

    // Arrays can keep .default([]) because RHF handles empty arrays fine, 
    // but .optional() is safer if you aren't rendering a field for it yet.
    features: z.array(z.string()).optional(),

    plateNumber: z.string().min(1, "License plate number is required"),

    // REMOVED .default()
    status: z.enum(["available", "rented", "maintenance"], "Status is required and must be one of: available, rented, maintenance"),

    // REMOVED .default()
    isActive: z.boolean(),
});