import { z } from "zod";

export const carInsertSchema = z.object({
    id: z.string().optional(), // ID generated by backend

    // --- BASIC INFO ---
    name: z.string().min(1, "Vehicle name is required"),
    make: z.string().min(1, "Make is required (e.g., Porsche)"),
    model: z.string().min(1, "Model is required (e.g., 911 Carrera)"),
    year: z
        .number()
        .int("Year must be a whole number")
        .min(1950, "Year is too old")
        .max(new Date().getFullYear() + 1, "Year cannot be too far in the future"),
    category: z.string().min(1, "Category is required"),

    // NEW: UI Fields for the details page
    tier: z.string().min(1, "Tier is required (e.g., Premium Tier)"),
    description: z.string().min(10, "Please provide a detailed description (min 10 chars)"),

    // --- FINANCIALS ---
    pricePerDay: z
        .number()
        .int("Price must be a whole number (no decimals)")
        .min(0, "Price per day must be a positive number"),

    // --- SPECS ---
    transmission: z.enum(["automatic", "manual"],
        "Please choose a transmission type"
    ),
    fuelType: z.enum(["petrol", "ev", "hybrid"],
        "Please choose a fuel type"
    ),
    seats: z
        .number()
        .int("Seats must be a whole number")
        .min(1, "Vehicle must have at least 1 seat")
        .max(60, "Exceeds maximum seat limit"),

    // --- MEDIA ---
    headerImage: z.url("Image must be a valid URL"), // Made required since the UI heavily depends on it
    imageUrls: z.array(z.url("Must be a valid URL")).optional(),
    features: z.array(z.string()).optional(),

    // --- OPERATIONS ---
    plateNumber: z.string().min(1, "License plate number is required"),
    status: z.enum(["available", "rented", "maintenance"],
        "Please choose a status for car"
    ),
    isActive: z.boolean(),
});