import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, index, pgEnum, integer, real } from "drizzle-orm/pg-core";

export const role = pgEnum("role", [
    "admin",
    "customer"
]);

// User table generated by better-auth's drizzle adapter
export const user = pgTable("user", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),

    // NEW: phone support (useful for OTP / contact)
    phone: text("phone"),

    emailVerified: boolean("email_verified").default(false).notNull(),

    // NEW: phone verification support
    phoneVerified: boolean("phone_verified").default(false),

    image: text("image"),
    createdAt: timestamp("created_at").defaultNow().notNull(),

    updatedAt: timestamp("updated_at")
        .defaultNow()
        .$onUpdate(() => /* @__PURE__ */ new Date())
        .notNull(),

    role: role("role").default("customer").notNull(),

    // NEW: soft delete / ban support
    isActive: boolean("is_active").default(true),

    // NEW: future 2FA support
    twoFactorEnabled: boolean("two_factor_enabled").default(false),

    // NEW: track last login (analytics / security)
    lastLoginAt: timestamp("last_login_at"),
}, (table) => [
    // NEW: index for faster lookups
    index("user_email_idx").on(table.email),

    // NEW: useful if phone login is added
    index("user_phone_idx").on(table.phone),
]);

// Session table generated by better-auth's drizzle adapter
export const session = pgTable(
    "session",
    {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at").notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at").defaultNow().notNull(),

        updatedAt: timestamp("updated_at")
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),

        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),

        // NEW: device + location tracking
        device: text("device"),
        location: text("location"),

        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
    },
    (table) => [
        index("session_userId_idx").on(table.userId),

        // NEW: faster token lookup
        index("session_token_idx").on(table.token),
    ],
);

// Account table generated by better-auth's drizzle adapter
export const account = pgTable(
    "account",
    {
        id: text("id").primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),

        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),

        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at"),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
        scope: text("scope"),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        password: text("password"),

        updatedAt: timestamp("updated_at")
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [
        index("account_userId_idx").on(table.userId),

        // NEW: useful for querying by provider (google, github, etc.)
        index("account_provider_idx").on(table.providerId),
    ],
);

// Verification table generated by better-auth's drizzle adapter
export const verification = pgTable(
    "verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),

        // NEW: distinguish verification types
        // e.g. email_verification | password_reset | otp
        type: text("type").notNull(),

        expiresAt: timestamp("expires_at").notNull(),
        createdAt: timestamp("created_at").defaultNow().notNull(),

        updatedAt: timestamp("updated_at")
            .defaultNow()
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [
        index("verification_identifier_idx").on(table.identifier),

        // NEW: faster token lookup
        index("verification_value_idx").on(table.value),
    ],
);

// Define relations between tables
// A user can have many sessions and accounts
export const userRelations = relations(user, ({ many }) => ({
    sessions: many(session),
    accounts: many(account),
}));

// A session belongs to one user
// An account belongs to one user
export const sessionRelations = relations(session, ({ one }) => ({
    user: one(user, {
        fields: [session.userId],
        references: [user.id],
    }),
}));

// An account belongs to one user
// A user can have many accounts
export const accountRelations = relations(account, ({ one }) => ({
    user: one(user, {
        fields: [account.userId],
        references: [user.id],
    }),
}));

export const carStatusEnum = pgEnum("car_status", ["available", "rented", "maintenance"]);

export const transmissionEnum = pgEnum("transmission", ["automatic", "manual"]);

export const fuelTypeEnum = pgEnum("fuel_type", ["petrol", "ev", "hybrid"]);

export const car = pgTable("car", {
    // --- IDENTIFICATION ---
    id: text("id").primaryKey(),
    name: text("name").notNull(),           // "Porsche 911 Carrera"
    make: text("make").notNull(),           // "Porsche" (Great for filtering)
    model: text("model").notNull(),         // "911 Carrera"
    year: integer("year").notNull(),        // 2024
    category: text("category").notNull(),   // "Luxury Sports"

    // --- FINANCIALS & METRICS ---
    // Store price as an integer (e.g., whole Rupees) for accurate math
    pricePerDay: integer("price_per_day").notNull(),
    // Store rating as a real number (e.g., 4.8) for > < filtering
    rating: real("rating").default(0).notNull(),

    // --- SPECIFICATIONS (The "Precision" Details) ---
    transmission: transmissionEnum("transmission").notNull(),
    fuelType: fuelTypeEnum("fuel_type").notNull(),
    seats: integer("seats").notNull(),

    // --- MEDIA & UX ---
    headerImage: text("headerImage").notNull(),
    imageUrls: text("imageUrls").array(),
    // Postgres arrays are amazing for listing features ("Sunroof", "Chauffeur", etc.)
    features: text("features").array(),

    // --- OPERATIONS & INVENTORY ---
    plateNumber: text("plate_number").unique().notNull(), // Every physical car needs a unique plate
    status: carStatusEnum("status").default("available").notNull(),
    isActive: boolean("is_active").default(true).notNull(), // Soft delete/hide from UI

    // --- AUDIT TIMESTAMPS ---
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
});

export const booking = pgTable("booking", {
    id: text("id").primaryKey(),
    userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }),
    carId: text("car_id").notNull().references(() => car.id, { onDelete: "cascade" }),
    startDate: timestamp("start_date").notNull(),
    endDate: timestamp("end_date").notNull(),
    totalPrice: integer("total_price").notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
});

export const bookingRelations = relations(booking, ({ one }) => ({
    user: one(user, {
        fields: [booking.userId],
        references: [user.id],
    }),
    car: one(car, {
        fields: [booking.carId],
        references: [car.id],
    }),
}));