import { relations } from "drizzle-orm";
import { pgTable, text, timestamp, boolean, index, pgEnum, integer, real } from "drizzle-orm/pg-core";
import { nanoid } from "nanoid";

export const role = pgEnum("role", [
    "admin",
    "customer"
]);

// User table generated by better-auth's drizzle adapter
export const user = pgTable("user", {
    id: text("id").primaryKey(),
    name: text("name").notNull(),
    email: text("email").notNull().unique(),

    // NEW: phone support (useful for OTP / contact)
    phone: text("phone"),

    emailVerified: boolean("email_verified").default(false).notNull(),

    // NEW: phone verification support
    phoneVerified: boolean("phone_verified").default(false),

    image: text("image"),
    createdAt: timestamp("created_at").defaultNow().notNull(),

    updatedAt: timestamp("updated_at")
        .defaultNow()
        .$onUpdate(() => /* @__PURE__ */ new Date())
        .notNull(),

    role: text("role").default("customer"),
    banned: boolean("banned").default(false),
    banReason: text("ban_reason"),
    banExpires: timestamp("ban_expires"),

    // NEW: soft delete / ban support
    isActive: boolean("is_active").default(true),

    // NEW: future 2FA support
    twoFactorEnabled: boolean("two_factor_enabled").default(false),

    // NEW: track last login (analytics / security)
    lastLoginAt: timestamp("last_login_at"),
}, (table) => [
    // NEW: index for faster lookups
    index("user_email_idx").on(table.email),

    // NEW: useful if phone login is added
    index("user_phone_idx").on(table.phone),
]);

// Session table generated by better-auth's drizzle adapter
export const session = pgTable(
    "session",
    {
        id: text("id").primaryKey(),
        expiresAt: timestamp("expires_at").notNull(),
        token: text("token").notNull().unique(),
        createdAt: timestamp("created_at").defaultNow().notNull(),

        updatedAt: timestamp("updated_at")
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),

        ipAddress: text("ip_address"),
        userAgent: text("user_agent"),

        // NEW: device + location tracking
        device: text("device"),
        location: text("location"),

        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),
        impersonatedBy: text("impersonated_by"),
    },
    (table) => [
        index("session_userId_idx").on(table.userId),

        // NEW: faster token lookup
        index("session_token_idx").on(table.token),
    ],
);

// Account table generated by better-auth's drizzle adapter
export const account = pgTable(
    "account",
    {
        id: text("id").primaryKey(),
        accountId: text("account_id").notNull(),
        providerId: text("provider_id").notNull(),

        userId: text("user_id")
            .notNull()
            .references(() => user.id, { onDelete: "cascade" }),

        accessToken: text("access_token"),
        refreshToken: text("refresh_token"),
        idToken: text("id_token"),
        accessTokenExpiresAt: timestamp("access_token_expires_at"),
        refreshTokenExpiresAt: timestamp("refresh_token_expires_at"),
        scope: text("scope"),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        password: text("password"),

        updatedAt: timestamp("updated_at")
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [
        index("account_userId_idx").on(table.userId),

        // NEW: useful for querying by provider (google, github, etc.)
        index("account_provider_idx").on(table.providerId),
    ],
);

// Verification table generated by better-auth's drizzle adapter
export const verification = pgTable(
    "verification",
    {
        id: text("id").primaryKey(),
        identifier: text("identifier").notNull(),
        value: text("value").notNull(),
        expiresAt: timestamp("expires_at").notNull(),
        createdAt: timestamp("created_at").defaultNow().notNull(),
        updatedAt: timestamp("updated_at")
            .defaultNow()
            .$onUpdate(() => /* @__PURE__ */ new Date())
            .notNull(),
    },
    (table) => [index("verification_identifier_idx").on(table.identifier)],
);

// Define relations between tables
// A user can have many sessions and accounts
export const userRelations = relations(user, ({ many }) => ({
    sessions: many(session),
    accounts: many(account),
    bookings: many(booking),
    auditLogs: many(auditLog),
}));

// A session belongs to one user
// An account belongs to one user
export const sessionRelations = relations(session, ({ one }) => ({
    user: one(user, {
        fields: [session.userId],
        references: [user.id],
    }),
}));

// An account belongs to one user
// A user can have many accounts
export const accountRelations = relations(account, ({ one }) => ({
    user: one(user, {
        fields: [account.userId],
        references: [user.id],
    }),
}));

// ----- Car and Booking Tables:

export const carStatusEnum = pgEnum("car_status", ["available", "rented", "maintenance"]);
export const transmissionEnum = pgEnum("transmission", ["automatic", "manual"]);
export const fuelTypeEnum = pgEnum("fuel_type", ["petrol", "ev", "hybrid"]);

// UPDATE: Added "cash" to the payment methods
export const paymentMethodEnum = pgEnum("payment_method", ["card", "wallet", "cash"]);
export const paymentStatusEnum = pgEnum("payment_status", ["unpaid", "paid", "refunded", "failed"]);
export const bookingStatusEnum = pgEnum("booking_status", ["pending", "confirmed", "cancelled", "completed", "expired"]);
export const auditActionEnum = pgEnum("audit_action", [
    "booking.confirmed",
    "booking.cancelled",
    "booking.completed",
    "booking.expired",
    "car.created",
    "car.updated",
    "car.deleted",
    "user.banned",
]);

// --- TABLES ---

export const location = pgTable("location", {
    id: text("id").primaryKey().$defaultFn(() => nanoid()),
    name: text("name").notNull(),
    city: text("city").notNull(),
    fullAddress: text("full_address").notNull(),
    isActive: boolean("is_active").default(true).notNull(),
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
});

export const car = pgTable("car", {
    // --- IDENTIFICATION ---
    id: text("id").primaryKey().$defaultFn(() => nanoid()),
    name: text("name").notNull(),
    make: text("make").notNull(),
    model: text("model").notNull(),
    year: integer("year").notNull(),
    category: text("category").notNull(),

    tier: text("tier").notNull().default("Standard"),
    description: text("description").notNull(),

    // --- FINANCIALS & METRICS ---
    pricePerDay: integer("price_per_day").notNull(),
    rating: real("rating").default(0).notNull(),

    // --- SPECIFICATIONS ---
    transmission: transmissionEnum("transmission").notNull(),
    fuelType: fuelTypeEnum("fuel_type").notNull(),
    seats: integer("seats").notNull(),

    // --- MEDIA & UX ---
    headerImage: text("header_image").notNull(),
    imageUrls: text("image_urls").array(),
    features: text("features").array(),

    // --- OPERATIONS & INVENTORY ---
    plateNumber: text("plate_number").unique().notNull(),
    locationId: text("location_id").notNull().references(() => location.id, { onDelete: "restrict" }),
    status: carStatusEnum("status").default("available").notNull(),
    isActive: boolean("is_active").default(true).notNull(),

    // --- RECORD TRACKING ---
    deletedAt: timestamp("deleted_at"),

    // --- AUDIT TIMESTAMPS ---
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
    index("car_status_category_idx").on(table.status, table.category),
    index("car_is_active_status_idx").on(table.isActive, table.status),
    index("car_price_per_day_idx").on(table.pricePerDay),
    index("car_plate_number_idx").on(table.plateNumber),
    index("car_location_id_idx").on(table.locationId),
]);


export const booking = pgTable("booking", {
    id: text("id").primaryKey().$defaultFn(() => nanoid()),
    userId: text("user_id").notNull().references(() => user.id, { onDelete: "cascade" }),
    carId: text("car_id").notNull().references(() => car.id, { onDelete: "cascade" }),

    // --- SCHEDULING ---
    startDate: timestamp("start_date").notNull(),
    endDate: timestamp("end_date").notNull(),

    // --- LOCATION ---
    pickUpLocation: text("pick_up_location").notNull().references(() => location.id, { onDelete: "restrict" }),
    dropOffLocation: text("drop_off_location").notNull().references(() => location.id, { onDelete: "restrict" }),

    // --- FORM: PERSONAL DETAILS ---
    fullName: text("full_name").notNull(),
    email: text("email").notNull(),
    phoneNumber: text("phone_number").notNull(),
    licenseNumber: text("license_number").notNull(),

    // --- FORM: PAYMENT ---
    // UPDATE: Set default to "cash"
    paymentMethod: paymentMethodEnum("payment_method").default("cash").notNull(),
    paymentIntentId: text("payment_intent_id"),
    paymentStatus: paymentStatusEnum("payment_status").default("unpaid").notNull(),

    // --- FINANCIAL BREAKDOWN ---
    dailyRate: integer("daily_rate").notNull(),
    days: integer("days").notNull(),
    protectionFee: integer("protection_fee").notNull(),
    surchargeFee: integer("surcharge_fee").notNull(),
    totalPrice: integer("total_price").notNull(),

    // --- STATUS ---
    status: bookingStatusEnum("status").default("pending").notNull(),

    cancelledAt: timestamp("cancelled_at"),
    cancelledBy: text("cancelled_by"),
    cancellationReason: text("cancellation_reason"),

    // --- AUDIT TIMESTAMPS ---
    createdAt: timestamp("created_at").defaultNow().notNull(),
    updatedAt: timestamp("updated_at").defaultNow().$onUpdate(() => new Date()).notNull(),
}, (table) => [
    // Composite index for fast booking conflict/overlap detection
    index("booking_car_dates_idx").on(table.carId, table.startDate, table.endDate),
    index("booking_user_id_created_at_idx").on(table.userId, table.createdAt),
    index("booking_status_created_at_idx").on(table.status, table.createdAt),
    index("booking_car_id_status_idx").on(table.carId, table.status),
]);

// --- RELATIONS ---
export const locationRelations = relations(location, ({ many }) => ({
    cars: many(car),
}));

export const bookingRelations = relations(booking, ({ one }) => ({
    user: one(user, {
        fields: [booking.userId],
        references: [user.id],
    }),
    car: one(car, {
        fields: [booking.carId],
        references: [car.id],
    }),
    pickUp: one(location, {
        fields: [booking.pickUpLocation],
        references: [location.id],
    }),
    dropOff: one(location, {
        fields: [booking.dropOffLocation],
        references: [location.id],
    }),
}));

export const carRelations = relations(car, ({ one, many }) => ({
    bookings: many(booking),
    location: one(location, {
        fields: [car.locationId],
        references: [location.id],
    }),
}));

export const auditLog = pgTable("audit_log", {
    id: text("id").primaryKey().$defaultFn(() => nanoid()),
    adminId: text("admin_id").references(() => user.id, { onDelete: "set null" }),
    adminName: text("admin_name"),
    adminEmail: text("admin_email"),
    action: auditActionEnum("action").notNull(),
    targetType: text("target_type").notNull(),
    targetId: text("target_id").notNull(),
    previousValue: text("previous_value"),
    newValue: text("new_value"),
    createdAt: timestamp("created_at").defaultNow().notNull(),
}, (table) => [
    index("audit_log_admin_id_idx").on(table.adminId),
    index("audit_log_target_idx").on(table.targetType, table.targetId),
    index("audit_log_created_at_idx").on(table.createdAt),
]);

export const auditLogRelations = relations(auditLog, ({ one }) => ({
    admin: one(user, { fields: [auditLog.adminId], references: [user.id] }),
}));